services:
  db:
    image: public.ecr.aws/docker/library/postgres:16-alpine
    container_name: foodcalories_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      target: prod
    container_name: foodcalories_backend
    env_file:
      - ./backend/.env
    restart: unless-stopped
    environment:
      - DEBUG=false
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    env_file:
      - ./frontend/.env
    build:
      context: ./frontend
      target: prod
    container_name: foodcalories_frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      # Add Nginx logs to follow later if anything interesting happens.
      - ./logs/nginx:/var/log/nginx

volumes:
  postgres_data:
