version: "3.9"

services:

  backend:
    build:
      context: ./backend
    container_name: foodcalories_backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      CORS_ORIGIN: http://localhost:5173
      ENVIRONMENT: production
      PORT: 8000
    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend
    container_name: foodcalories_frontend
    ports:
      - "3000:80"
    depends_on:
      - "backend"
