/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/foods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Foods */
        get: operations["query_foods_v1_foods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Add Meal
         * @description Creates a new meal data and sends it into the database
         */
        put: operations["add_meal_v1_meal_put"];
        post?: never;
        /**
         * Delete Meal
         * @description given a meal id, deletes a user meal
         */
        delete: operations["delete_meal_v1_meal_delete"];
        options?: never;
        head?: never;
        /**
         * Update Meal
         * @description Update a meal value from a specific user
         */
        patch: operations["update_meal_v1_meal_patch"];
        trace?: never;
    };
    "/v1/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Meals By Date Start End Date
         * @description Returns all the meals the user has consumed in a specific date, or between a range of dates.
         */
        get: operations["get_meals_by_date_start_end_date_v1_meals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description given a username and password, creates a new user inside the database
         *     if the user doesn't already exist inside our databse, we'd like to create one for the client
         *     so he can access the service
         */
        post: operations["register_v1_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/currentUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description returns the current user after being logged with an JWT access token.
         *     should return the a user id, and its role.
         *
         *     if the user isn't authenticated, it'll return 401
         */
        get: operations["get_current_user_v1_currentUser_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login Endpoint for users to the service,
         *     to be able to get both the refresh token and access token.
         *
         *     returns forbidden HTTP if the credentials doesn't exist.
         */
        post: operations["login_v1_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description returns a new access token to the user after it's expired using the refresh_token.
         *     the access token will be received in the response.
         */
        post: operations["refresh_v1_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Test */
        get: operations["test__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_v1_token_post */
        Body_login_v1_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * FoodDetail
         * @description A Pydantic model that shows what information to expect from a query on food from food items
         *
         *     curently,
         *     the model receives not only information about basic nutrients of a specific food,
         *     but also the name of it, the id of the food
         *
         *     and different ways to "size it up"
         */
        FoodDetail: {
            /** Code */
            code: number;
            /** Shmmitzrach */
            shmmitzrach: string;
            /** Protein */
            protein: number;
            /** Total Fat */
            total_fat: number;
            /** Carbohydrates */
            carbohydrates?: number | null;
            /** Food Energy */
            food_energy: number;
            /** Midot */
            midot: components["schemas"]["PortionSize"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JWTAccessBase
         * @description A pydantic model for FASTAPI endpoints that contains the credential parts of the access token
         *     Whenever we receive a Access token, this are the values I expect it to contain.
         *
         *     sub: the id of the username
         *     role: the current user role (ADMIN / USER)
         *     exp: the expiration date of the refresh token
         */
        JWTAccessBase: {
            /** Sub */
            sub: number;
            /** Role */
            role: string;
        };
        /**
         * LoginTokenResponse
         * @description Login Response of /login endpoint,
         *     returns the JWT Access token and the token type.
         */
        LoginTokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * MealEntry
         * @description An API Model For Returning What the person ate in a specific day.
         *     code_id: the ID of the food item eaten, which is a foreign key to MohMitzrachim.code.
         *     mida_id: the ID of the unit of measurement, which is a foreign key to YehidotMida
         *     amount: the amount of the food eaten, which is used to calculate the calories of the meal.
         *     meal_type: the type of meal eaten(breakfast, lunch, dinner), which is used to categorize the meals eaten by the user.
         */
        MealEntry: {
            /** Food Id */
            food_id: number;
            /** Mida Id */
            mida_id: number;
            /** Amount */
            amount: number;
            meal_type: components["schemas"]["MealType"];
        };
        /** MealEntryResponse */
        MealEntryResponse: {
            /** Food Name */
            food_name: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Protein */
            protein: number;
            /** Total Fat */
            total_fat: number;
            /** Carbohydrates */
            carbohydrates?: number | null;
            /** Food Energy */
            food_energy: number;
            mida: components["schemas"]["MeasurementUnit"];
            /** Meal Id */
            meal_id: number;
            /** Amount */
            amount: number;
            /** Mishkal */
            mishkal: number;
            meal_type: components["schemas"]["MealType"];
        };
        /**
         * MealType
         * @description An Enum Class which is saved inside meals_eaten,
         *     to determine which type of meal the user has eaten while writing to the database
         * @enum {string}
         */
        MealType: "breakfast" | "lunch" | "dinner";
        /**
         * MeasurementUnit
         * @description The base model for a Yehida (unit of measurement) in the food system.
         *
         *     - smlmida: the ID of the unit of measurement inside DB
         *     - shmmida: the name of the unit of measurement inside DB
         */
        MeasurementUnit: {
            /** Smlmida */
            smlmida: number;
            /** Shmmida */
            shmmida: string | null;
        };
        /**
         * Message
         * @description The current class contains a base of how our HTTP errors would look like.
         *     since fastAPI doesn't know which HTTP errors a function throws, this is currently the only way.
         *
         *     https://fastapi.tiangolo.com/advanced/additional-responses/#additional-response-with-model
         */
        Message: {
            /** Message */
            message: string;
        };
        /**
         * PortionSize
         * @description A model representing the relationship between a food item (MohMitzrach) and its unit of measurement (Yehida).
         *     This model is used to calculate the calories of a meal by connecting the food item with its
         *     unit of measurement and the weight of that unit in grams.
         *     Currently the values are
         *
         *     id: The id of the current mida from the Yehidot Table.
         *     name: The current name from the Yehidot table
         *     mishkal: Given the mishkal and the food item, how many grams does this mida count as?
         */
        PortionSize: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Mishkal */
            mishkal: number;
        };
        /**
         * UserRegister
         * @description A Model to create valid user in our database  with a valid username and password.
         *     Used wants to register (regularly via the /register endpoint)
         *
         *     Expected to receieve a username that is not already in the database,
         *     and a valid username (minimum 8 characters, 1 special character, 1 digit)
         */
        UserRegister: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    query_foods_v1_foods_get: {
        parameters: {
            query: {
                food_query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodDetail"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_meal_v1_meal_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealEntry"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_v1_meal_delete: {
        parameters: {
            query: {
                meal_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meal_v1_meal_patch: {
        parameters: {
            query: {
                meal_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealEntry"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meals_by_date_start_end_date_v1_meals_get: {
        parameters: {
            query: {
                date: string;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealEntryResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_v1_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_v1_currentUser_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JWTAccessBase"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    login_v1_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_v1_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginTokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_v1_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginTokenResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
