"""make db allow oauth support

Revision ID: 240eacd56da0
Revises: f0d4290e3f65
Create Date: 2026-04-03 01:26:41.825234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from haikunator import Haikunator

# revision identifiers, used by Alembic.
revision: str = "240eacd56da0"
down_revision: Union[str, Sequence[str], None] = "f0d4290e3f65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_moh_mitzrachim_search_name"),
        table_name="moh_mitzrachim",
        postgresql_ops={"search_name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=True
    )

    # Create the oauth_users table
    op.create_table(
        "oauth_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", "provider", "provider_user_id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )

    # Setting up the user_profile table to have a name_display column, which is an optional display name for the user profile.
    # After setting nullable, we will feel the name_display with different names, and then move to make it non-nullable, and then we will have a display name for all the user profiles.
    op.add_column(
        "user_profile", sa.Column("name_display", sa.String(length=255), nullable=True)
    )

    connection = op.get_bind()

    rows = connection.execute(sa.text("SELECT id FROM user_profile")).fetchall()
    haikunator = Haikunator()

    for row in rows:
        display_name = haikunator.haikunate()
        connection.execute(
            sa.text("UPDATE user_profile SET name_display = :name WHERE id = :id"),
            {"name": display_name, "id": row[0]},
        )
    op.alter_column(
        "user_profile", "name_display", existing_type=sa.String(255), nullable=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.drop_column("user_profile", "name_display")
    op.drop_table("oauth_users")
    op.create_index(
        op.f("idx_moh_mitzrachim_search_name"),
        "moh_mitzrachim",
        ["search_name"],
        unique=False,
        postgresql_ops={"search_name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
