"""on user delete, make cascade other tables

Revision ID: 5de2d85f51a2
Revises: c58f2194a48d
Create Date: 2026-04-01 18:33:42.114442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de2d85f51a2'
down_revision: Union[str, Sequence[str], None] = 'c58f2194a48d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('meals_eaten_user_id_fkey'), 'meals_eaten', type_='foreignkey')
    op.create_foreign_key(op.f('meals_eaten_user_id_fkey'), 'meals_eaten', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('roles_user_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('roles_user_id_fkey'), 'roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_nutrition_profile_user_id_fkey'), 'user_nutrition_profile', type_='foreignkey')
    op.create_foreign_key(op.f('user_nutrition_profile_user_id_fkey'), 'user_nutrition_profile', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_profile_user_id_fkey'), 'user_profile', type_='foreignkey')
    op.create_foreign_key(op.f('user_profile_user_id_fkey'), 'user_profile', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('weight_history_user_id_fkey'), 'weight_history', type_='foreignkey')
    op.create_foreign_key(op.f('weight_history_user_id_fkey'), 'weight_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('weight_history_user_id_fkey'), 'weight_history', type_='foreignkey')
    op.create_foreign_key(op.f('weight_history_user_id_fkey'), 'weight_history', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('user_profile_user_id_fkey'), 'user_profile', type_='foreignkey')
    op.create_foreign_key(op.f('user_profile_user_id_fkey'), 'user_profile', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('user_nutrition_profile_user_id_fkey'), 'user_nutrition_profile', type_='foreignkey')
    op.create_foreign_key(op.f('user_nutrition_profile_user_id_fkey'), 'user_nutrition_profile', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('roles_user_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('roles_user_id_fkey'), 'roles', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('meals_eaten_user_id_fkey'), 'meals_eaten', type_='foreignkey')
    op.create_foreign_key(op.f('meals_eaten_user_id_fkey'), 'meals_eaten', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
