"""add search_name column for easier food search

Revision ID: f0d4290e3f65
Revises: 5de2d85f51a2
Create Date: 2026-04-01 23:36:06.861223

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0d4290e3f65"
down_revision: Union[str, Sequence[str], None] = "5de2d85f51a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "moh_mitzrachim",
        sa.Column("search_name", sa.String(length=255), nullable=True),
    )
    op.execute(
        "UPDATE moh_mitzrachim SET search_name = regexp_replace(shmmitzrach, '[^\\w\\s]', '', 'g')"
    )
    op.alter_column("moh_mitzrachim", "search_name", nullable=False)

    # https://www.postgresql.org/docs/9.0/pgtrgm.html
    # Add pg_trgm extension and create GIN index on search_name for faster search
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # Create a GIN index on the search_name column for faster search performance
    op.execute(
        "CREATE INDEX idx_moh_mitzrachim_search_name ON moh_mitzrachim USING gin (search_name gin_trgm_ops)"
    )
    # Lower the similarity threshold so the % operator returns more fuzzy matches
    # (default is 0.3, which is too strict for Hebrew food name searches).
    # ALTER DATABASE persists across all future sessions, unlike SET which is session-only.
    db_name = op.get_bind().execute(text("SELECT current_database()")).scalar()
    op.execute(f'ALTER DATABASE "{db_name}" SET pg_trgm.similarity_threshold = 0.1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reset similarity threshold back to PostgreSQL default
    db_name = op.get_bind().execute(text("SELECT current_database()")).scalar()
    op.execute(f'ALTER DATABASE "{db_name}" RESET pg_trgm.similarity_threshold')

    op.execute("DROP INDEX IF EXISTS idx_moh_mitzrachim_search_name")

    op.drop_column("moh_mitzrachim", "search_name")

    op.execute("DROP EXTENSION IF EXISTS pg_trgm")

    # ### end Alembic commands ###
